# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new  --gpu_nums 8 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 0 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new  --gpu_nums 8 --kv_cache_eviction true --capacity 128 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -3 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 0 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_3000  --gpu_nums 8 --kv_cache_eviction true --capacity 96 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -4 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 3000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_2000  --gpu_nums 8 --kv_cache_eviction true --capacity 64 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -6 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 2000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_3000  --gpu_nums 8 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 3000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_2000  --gpu_nums 8 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 2000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_3000  --gpu_nums 8 --kv_cache_eviction true --capacity 192 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -2 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 3000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_2000  --gpu_nums 8 --kv_cache_eviction true --capacity 128 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -3 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 2000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new  --gpu_nums 8 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 0 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new  --gpu_nums 8 --kv_cache_eviction true --capacity 128 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -3 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 0 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_3000  --gpu_nums 8 --kv_cache_eviction true --capacity 96 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -4 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 3000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_2000  --gpu_nums 8 --kv_cache_eviction true --capacity 64 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -6 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 2000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_3000  --gpu_nums 8 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 3000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --parallel_pattern every_window_query_input_query_anchor_new_label_2000  --gpu_nums 8 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 2000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true


# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new  --gpu_nums 6 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 0 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new  --gpu_nums 6 --kv_cache_eviction true --capacity 128 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -3 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 0 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new_label_3000  --gpu_nums 6 --kv_cache_eviction true --capacity 96 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -4 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 3000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new_label_2000  --gpu_nums 6 --kv_cache_eviction true --capacity 64 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -6 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 2000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new_label_6000  --gpu_nums 6 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 6000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new_label_3000  --gpu_nums 6 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 8  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 3000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new  --gpu_nums 8 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 0 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new  --gpu_nums 8 --kv_cache_eviction true --capacity 128 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -3 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 0 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new_label_3000  --gpu_nums 8 --kv_cache_eviction true --capacity 96 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -4 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 3000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new_label_2000  --gpu_nums 8 --kv_cache_eviction true --capacity 64 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -6 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 2000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new_label_3000  --gpu_nums 8 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 3000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true

# bash run_test_longbench_multi_gpu_window8_llama2.sh --model /home/avnet/.cache/huggingface/hub/Meta-Llama-3-8B-Instruct --parallel_pattern every_window_query_input_query_anchor_new_label_2000  --gpu_nums 8 --kv_cache_eviction true --capacity 384 --kv_cache_dynamic false --stage_eviction false --recent_token 4  --topk_windows -1 --query_rank true --query_recent_tokens 0 --get_recent_attn false --recent_top_num 0 --reduce_length false --reduce_factor 2000 --position_shift false --shift_factor 0 --interval_shift 0 --key_no_rope false --positional_sorting None --rank_ascend true --delete_context_prompt false  --in_eager_mode false --attn_avg false  --input_stitching False --calibration_stage None --calibration_mode 0 --special_token true